### ISSUE TITLE
Video input format specification

### ISSUE THREAD

**Issue by chatdeschroedinger** [Ericsson/PXNR-No-reference-video-quality-estimation#9]
Hi,

I have a question about the input format when using my own videos as input.

Which parameters should we adjust in `PXNR-model.py` or other files if we use our own video and how exactly?
In particular two parameters are unclear to me:

**Resolution**: 
In this [issue](https://github.com/Ericsson/PXNR-No-reference-video-quality-estimation/issues/8) you stated that different pixel and resolution formats can be entered manually. Does that mean I should adapt the width and height argument of `YUVSourceFFmpeg()` to the one of the video like eg 720x1080? 
Since in the [report](https://www.itu.int/pub/T-TUT-OPAVQ-2019-PSNTR) you specify that "video input file or bit stream is decoded and scaled to 3840x2160" I would assume the height and width argument of `YUVSourceFFmpeg()` must remain 3840 and 2160?

**Length:**
In the [report](https://www.itu.int/pub/T-TUT-OPAVQ-2019-PSNTR) you specify that the input video should be max 20s but the BigBuckBunny.mp4 is 8s. What are the exact requirements on input videos?

Thanks you for your response.

**Comment by davidlindero** [comment]
Res:
Yes, exactly, the resolution should be kept at 3840x2160. Only the parameters immediately below the 

"""
Sample variables, should be extracted from input video file. One way to get this
info is to run ffprobe on the video file first and parse the output manually.
"""

section has to be changed to match your video. I.e. framerate, pixel format, bit-depth and duration. 

Length: 
It's a bit tricky question to answer simply.. The algorithm has been optimised for videos 8-10s and mainly validated on this. Using clips longer than 20s goes far beyond what pxnr has been designed for and the sampling gets way too sparse then so that the chance to miss a quality change gets too high. If you look through the code, PXNR only uses 96 frames from the whole clip (first, last, and 94 frames spread evenly in between), so with too long clips the number of examined frames /s gets too low.

**Comment by chatdeschroedinger** [comment]
thank you for that detailed response!

Ok so as far as I understand PXNR takes 96 evenly spaced frames over the duration of the video which also requires a certain min length to achieve this.


For anybody who wants to use ffprobe this is what I used:

`ffprobe -v quiet -print_format json -show_format -show_streams 'video.mp4' > thevideo.json`
